openapi: 3.0.1
info:
  contact:
    email: anton.perhunov@aspose.com
    name: Aspose
  license:
    name: MIT License (MIT)
    url: https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt
  termsOfService: https://about.groupdocs.cloud/legal/tos/
  title: GroupDocs.Translation SDK
  version: 23.9.2
servers:
- description: GroupDocs.Translation server
  url: https://api.groupdocs.cloud/v2.0/translation/
security:
- JWT: []
paths:
  /spreadsheets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpreadsheetFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /csv:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CsvFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /html:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtmlFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /markdown:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarkdownFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /hugo:
    get:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudHugoResponse'
          description: Success
      tags:
      - Translation
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HugoRequest'
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Accepted
      tags:
      - Translation
  /image-to-file:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OcrFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /image-to-text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OcrTextRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /pdf:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PdfFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /resx:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResxFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /presentation:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PresentationFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /hc:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckStatus'
          description: Success
      tags:
      - Translation
  /languages:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LanguagePairData'
                type: array
          description: Success
      tags:
      - Translation
  /auto:
    post:
      requestBody:
        content:
          application/json:
            encoding:
              Format:
                style: form
              OutputFormat:
                style: form
              Masters:
                style: form
              Formatting:
                style: form
              Route:
                style: form
              Separator:
                style: form
              Elements:
                style: form
              Ranges:
                style: form
              ShortCodeList:
                style: form
              FrontMatterList:
                style: form
              SourceLanguage:
                style: form
              TargetLanguages:
                style: form
              File:
                style: form
              OriginalFileName:
                style: form
              Url:
                style: form
              Origin:
                style: form
              SavingMode:
                style: form
            schema:
              $ref: '#/components/schemas/_auto_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
  /document/{requestId}:
    get:
      parameters:
      - explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudFileResponse'
          description: Success
      tags:
      - Translation
  /text/{requestId}:
    get:
      parameters:
      - explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudTextResponse'
          description: Success
      tags:
      - Translation
  /document:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextDocumentFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      tags:
      - Translation
components:
  schemas:
    CloudFileResponse:
      additionalProperties: false
      example:
        urls:
          key:
            size: 0
            url: url
        scores:
          key: 6.0274563
        message: message
        status: null
      properties:
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          nullable: true
          type: string
        urls:
          additionalProperties:
            $ref: '#/components/schemas/UrlFileInfo'
          nullable: true
          type: object
        scores:
          additionalProperties:
            format: float
            nullable: true
            type: number
          nullable: true
          type: object
      type: object
    CloudHugoResponse:
      additionalProperties: false
      example:
        frontmatters:
        - - frontmatters
          - frontmatters
        - - frontmatters
          - frontmatters
        shortcodes:
          key:
          - - shortcodes
            - shortcodes
          - - shortcodes
            - shortcodes
        message: message
        status: null
      properties:
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          nullable: true
          type: string
        frontmatters:
          items:
            items:
              type: string
            type: array
          nullable: true
          type: array
        shortcodes:
          additionalProperties:
            items:
              items:
                type: string
              type: array
            nullable: true
            type: array
          nullable: true
          type: object
      type: object
    CloudTextResponse:
      additionalProperties: false
      example:
        translations:
          key:
          - translations
          - translations
        message: message
        status: null
      properties:
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          nullable: true
          type: string
        translations:
          additionalProperties:
            items:
              type: string
            nullable: true
            type: array
          nullable: true
          type: object
      type: object
    CsvFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        origin: origin
        savingMode: Files
        format: Csv
        outFormat: outFormat
        separator: separator
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        format:
          default: Csv
          enum:
          - Unknown
          - Csv
          - Tsv
          type: string
        outFormat:
          minLength: 1
          type: string
        separator:
          nullable: true
          type: string
      required:
      - outFormat
      - sourceLanguage
      - targetLanguages
      type: object
    HealthCheckStatus:
      additionalProperties: false
      example:
        cloudStatus: cloudStatus
        kafkaDeliveryStatus: kafkaDeliveryStatus
      properties:
        kafkaDeliveryStatus:
          nullable: true
          type: string
        cloudStatus:
          nullable: true
          type: string
      type: object
    HtmlFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        origin: origin
        savingMode: Files
        outputFormat: outputFormat
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        outputFormat:
          minLength: 1
          type: string
      required:
      - File
      - Source
      - Targets
      type: object
    HttpStatusCode:
      enum:
      - Continue
      - SwitchingProtocols
      - Processing
      - EarlyHints
      - OK
      - Created
      - Accepted
      - NonAuthoritativeInformation
      - NoContent
      - ResetContent
      - PartialContent
      - MultiStatus
      - AlreadyReported
      - IMUsed
      - MultipleChoices
      - MovedPermanently
      - Found
      - SeeOther
      - NotModified
      - UseProxy
      - Unused
      - TemporaryRedirect
      - PermanentRedirect
      - BadRequest
      - Unauthorized
      - PaymentRequired
      - Forbidden
      - NotFound
      - MethodNotAllowed
      - NotAcceptable
      - ProxyAuthenticationRequired
      - RequestTimeout
      - Conflict
      - Gone
      - LengthRequired
      - PreconditionFailed
      - RequestEntityTooLarge
      - RequestUriTooLong
      - UnsupportedMediaType
      - RequestedRangeNotSatisfiable
      - ExpectationFailed
      - MisdirectedRequest
      - UnprocessableEntity
      - Locked
      - FailedDependency
      - UpgradeRequired
      - PreconditionRequired
      - TooManyRequests
      - RequestHeaderFieldsTooLarge
      - UnavailableForLegalReasons
      - InternalServerError
      - NotImplemented
      - BadGateway
      - ServiceUnavailable
      - GatewayTimeout
      - HttpVersionNotSupported
      - VariantAlsoNegotiates
      - InsufficientStorage
      - LoopDetected
      - NotExtended
      - NetworkAuthenticationRequired
      type: string
    HugoRequest:
      additionalProperties: false
      example:
        file: file
        url: url
      properties:
        file:
          format: byte
          nullable: true
          type: string
        url:
          nullable: true
          type: string
      type: object
    LanguagePairData:
      additionalProperties: false
      example:
        source: source
        targets:
        - targets
        - targets
      properties:
        source:
          nullable: true
          type: string
        targets:
          items:
            type: string
          nullable: true
          type: array
      type: object
    MarkdownFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        frontMatterList:
        - - frontMatterList
          - frontMatterList
        - - frontMatterList
          - frontMatterList
        file: file
        shortCodeList:
          key:
          - - shortCodeList
            - shortCodeList
          - - shortCodeList
            - shortCodeList
        origin: origin
        savingMode: Files
        outputFormat: outputFormat
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        outputFormat:
          minLength: 1
          type: string
        shortCodeList:
          additionalProperties:
            items:
              items:
                type: string
              type: array
            nullable: true
            type: array
          nullable: true
          type: object
        frontMatterList:
          items:
            items:
              type: string
            type: array
          nullable: true
          type: array
      required:
      - outputFormat
      - sourceLanguage
      - targetLanguages
      type: object
    OcrFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        origin: origin
        format: Unknown
        url: url
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        ocrformat: Pdf
        route: route
        pages:
        - 6
        - 6
        savingMode: Files
        rotationAngle: 0
        outputFormat: outputFormat
        sourceLanguage: en
        formatting: true
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        format:
          default: Unknown
          enum:
          - Unknown
          - Bmp
          - Jpg
          - Png
          - Svg
          - Gif
          - Pdf
          type: string
        ocrformat:
          default: Pdf
          enum:
          - Pdf
          - Xlsx
          - Csv
          type: string
        outputFormat:
          minLength: 1
          type: string
        rotationAngle:
          format: int32
          type: integer
        formatting:
          default: true
          type: boolean
        route:
          nullable: true
          type: string
        pages:
          items:
            format: int32
            type: integer
          nullable: true
          type: array
      required:
      - ocrformat
      - outputFormat
      - sourceLanguage
      - targetLanguages
      type: object
    OcrTextRequest:
      additionalProperties: false
      example:
        rotate: 0
        file: file
        route: route
        origin: origin
        format: Unknown
        source: en
        targets:
        - targets
        - targets
        url: url
        ishandwritten: true
      properties:
        format:
          default: Unknown
          enum:
          - Unknown
          - Bmp
          - Jpg
          - Png
          - Svg
          - Gif
          - Pdf
          type: string
        source:
          default: en
          minLength: 1
          type: string
        targets:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        rotate:
          format: int32
          type: integer
        ishandwritten:
          type: boolean
        origin:
          nullable: true
          type: string
        route:
          nullable: true
          type: string
      required:
      - File
      - Source
      - Targets
      type: object
    PdfFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        pages:
        - 0
        - 0
        origin: origin
        savingMode: Files
        preserveFormatting: true
        outputFormat: outputFormat
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        outputFormat:
          minLength: 1
          type: string
        preserveFormatting:
          default: true
          type: boolean
        pages:
          items:
            format: int32
            type: integer
          nullable: true
          type: array
      required:
      - outputFormat
      - sourceLanguage
      - targetLanguages
      type: object
    PresentationFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        slides:
        - 0
        - 0
        file: file
        origin: origin
        savingMode: Files
        format: Pptx
        masters: false
        outputFormat: outputFormat
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        format:
          default: Pptx
          enum:
          - Unknown
          - Ppt
          - Pptx
          - Pptm
          - Odp
          type: string
        outputFormat:
          minLength: 1
          type: string
        masters:
          default: false
          type: boolean
        slides:
          items:
            format: int32
            type: integer
          nullable: true
          type: array
      required:
      - File
      - Source
      - Targets
      type: object
    ResxFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        origin: origin
        savingMode: Files
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
      required:
      - sourceLanguage
      - targetLanguages
      type: object
    SpreadsheetFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        worksheets:
        - 0
        - 0
        ranges:
          key:
            ranges:
            - item2: item2
              item1: item1
            - item2: item2
              item1: item1
            columns:
            - 1
            - 1
            rows:
            - 6
            - 6
        origin: origin
        savingMode: Files
        format: Xlsx
        outputFormat: Xls
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        origin:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        format:
          default: Xlsx
          enum:
          - Unknown
          - Xls
          - Xlsx
          - Xlsm
          - Ods
          type: string
        outputFormat:
          enum:
          - Xls
          - Xlsx
          - Xlsm
          - Xlsb
          - Html
          - Pdf
          - Xps
          - Ods
          - Md
          - Docx
          - Pptx
          - Tiff
          type: string
        worksheets:
          items:
            format: int32
            type: integer
          nullable: true
          type: array
        ranges:
          additionalProperties:
            $ref: '#/components/schemas/WorksheetData'
          nullable: true
          type: object
      required:
      - format
      - outputFormat
      - sourceLanguage
      - targetLanguages
      type: object
    StatusResponse:
      additionalProperties: false
      example:
        id: id
        message: message
        status: null
      properties:
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          nullable: true
          type: string
        id:
          nullable: true
          type: string
      type: object
    StringStringTuple:
      additionalProperties: false
      example:
        item2: item2
        item1: item1
      properties:
        item1:
          type: string
        item2:
          type: string
      type: object
    TextDocumentFileRequest:
      additionalProperties: false
      example:
        originalFileName: originalFileName
        targetLanguages:
        - targetLanguages
        - targetLanguages
        file: file
        savingMode: Files
        origin: origin
        format: Docx
        preserveFormatting: true
        outputFormat: outputFormat
        sourceLanguage: en
        url: url
      properties:
        sourceLanguage:
          default: en
          minLength: 1
          type: string
        targetLanguages:
          items:
            type: string
          type: array
        file:
          format: byte
          nullable: true
          type: string
        originalFileName:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        savingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
        format:
          default: Docx
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Txt
          - Rtf
          - Odt
          type: string
        outputFormat:
          minLength: 1
          type: string
        preserveFormatting:
          default: true
          type: boolean
        origin:
          nullable: true
          type: string
      required:
      - format
      - outputFormat
      - sourceLanguage
      - targetLanguages
      type: object
    TextRequest:
      additionalProperties: false
      example:
        targetLanguages:
        - targetLanguages
        - targetLanguages
        texts:
        - texts
        - texts
        origin: origin
        containsMarkdown: true
        sourceLanguage: sourceLanguage
      properties:
        sourceLanguage:
          nullable: true
          type: string
        targetLanguages:
          items:
            type: string
          nullable: true
          type: array
        texts:
          items:
            type: string
          nullable: true
          type: array
        origin:
          nullable: true
          type: string
        containsMarkdown:
          type: boolean
      type: object
    UrlFileInfo:
      additionalProperties: false
      example:
        size: 0
        url: url
      properties:
        url:
          nullable: true
          type: string
        size:
          format: int64
          type: integer
      type: object
    WorksheetData:
      additionalProperties: false
      example:
        ranges:
        - item2: item2
          item1: item1
        - item2: item2
          item1: item1
        columns:
        - 1
        - 1
        rows:
        - 6
        - 6
      properties:
        rows:
          items:
            format: int32
            type: integer
          nullable: true
          type: array
        columns:
          items:
            format: int32
            type: integer
          nullable: true
          type: array
        ranges:
          items:
            $ref: '#/components/schemas/StringStringTuple'
          nullable: true
          type: array
      type: object
    _auto_post_request:
      properties:
        Format:
          default: Unknown
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Xls
          - Xlsx
          - Xlsm
          - Ppt
          - Pptx
          - Pptm
          - Txt
          - Pdf
          - Md
          - Resx
          - Html
          - Rtf
          - Odt
          - Ods
          - Odp
          - Csv
          - Tsv
          type: string
        OutputFormat:
          type: string
        Masters:
          default: false
          type: boolean
        Formatting:
          default: true
          type: boolean
        Route:
          type: string
        Separator:
          type: string
        Elements:
          items:
            format: int32
            type: integer
          type: array
        Ranges:
          additionalProperties:
            $ref: '#/components/schemas/WorksheetData'
          type: object
        ShortCodeList:
          additionalProperties:
            items:
              items:
                type: string
              type: array
            nullable: true
            type: array
          type: object
        FrontMatterList:
          items:
            items:
              type: string
            type: array
          type: array
        SourceLanguage:
          default: en
          type: string
        TargetLanguages:
          items:
            type: string
          type: array
        File:
          format: byte
          type: string
        OriginalFileName:
          type: string
        Url:
          type: string
        Origin:
          type: string
        SavingMode:
          enum:
          - Files
          - Archive
          - Both
          type: string
      required:
      - Format
      - OutputFormat
      - SourceLanguage
      - TargetLanguages
      type: object
  securitySchemes:
    JWT:
      description: Please enter APP SID & KEY
      flows:
        clientCredentials:
          authorizationUrl: https://id.groupdocs.cloud/
          scopes: {}
          tokenUrl: https://id.groupdocs.cloud/connect/token
      type: oauth2

